### ISSUE TITLE
Smartnode disregards specified gas price on subsequent transactions

### ISSUE THREAD

**Issue by sckuzzle** [rocket-pool/smartnode#494] opened 2024-04-16 04:31 UTC
I distributed the balance of my minipools with `rocketpool m d`, typing "1" afterwards for all of my minipools and then specifying a maximum gas price of 7.  This gas price was effective for the first minipool distribution, but every distribution after that ignored the specified gas price.  The expected behavior would be to use the specified gas price for every transaction.  

Correct gas: 0x03d700538721c071e73097acbbc7c6f514be4e5ba8afe5d5ed5ab74b4b5c34a8

Incorrect gas: 0x3ea5b5fe93aa783c1d11918e37dcae80d73121dc23814ee619f5143438e41d1f

Additional transactions can be viewed here: https://etherscan.io/txs?a=0xcd657d8f2e5ab70372e2700bbd6474413fb63871

**Comment by jshufro** [comment] 2024-04-16 04:43
Duplicate of https://github.com/rocket-pool/smartnode/issues/194

I'll ping the team about it. I opened a pr to fix it 2 years ago. I think it's still valid - https://github.com/rocket-pool/smartnode/pull/195

**Comment by 0xfornax** [comment] 2024-06-06 21:09
PR Merged.

**Closed by 0xfornax** 2024-06-06 21:09 UTC
