### ISSUE TITLE
The command "rocketpool service stop" should be renamed

### ISSUE THREAD

**Issue by kidkal** [rocket-pool/smartnode#57] opened 2020-10-08 21:30 UTC
Gday mates!!!! Righto, me and a couple of fellas got our knickers in a bit of a twist with this command here:
`rocketpool service stop`
See, we thought it just stops the service but nawww, it brings down the whole bloody lot!  So all the hard yards me and my fellas went through to sync up our nodes just disappeared like a possum with its tail on fire!

Righto, so if you fellas can be arsed, maybe change it to.. dunno..
`rocketpool service down` or `rocketpool service teardown`

See, it's just a knock off from `docker-compose down`, which means to remove all volumes etc.  And also, `pause` means something slightly different from `stop` in docker as well.

It'll be a good get if you fellas can pull this off!  We'll have a couple of rounds with you fellas when it's all over!
Hooroo!

**Comment by moles1** [comment] 2020-10-08 22:22
Duplicate of https://github.com/rocket-pool/smartnode/issues/52

**Closed by moles1** 2020-10-08 22:22 UTC
